export enum ActionType {
  SIZE_CHANGED = 'SIZE_CHANGED',
  BOARD_CREATED = 'BOARD_CREATED',
  CELLS_UPDATED = 'CELLS_UPDATED',
  CELL_UPDATED = 'CELL_UPDATED',
  IS_PLAYING = 'IS_PLAYING',
  IS_ON_PAUSE = 'IS_ON_PAUSE',
  BOARD_CLEARED = 'BOARD_CLEARED',
}
